plugins {
    id 'java-library'
    id 'maven-publish'
    // id 'org.openrewrite.rewrite' version '7.1.5'
}

group = 'net.infordata'
version = '1.0.2'

publishing {
    repositories {
        maven {
            url DISO21_THIRD_PARTY_REPOSITORY
            credentials {
                username "$nexusUserName"
                password "$nexusUserPassword"
            }
        }
    }
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
//    publications {
//        maven(MavenPublication) {
//            version = "${project.version}-${project.extensions.buildNumber.get()}"
//            artifact distZip
//        }
//    }
}



java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


repositories {
    maven {
        url DISO21_THIRD_PARTY_REPOSITORY
        credentials {
            username "$nexusUserName"
            password "$nexusUserPassword"
        }
    }
    maven {
        url DISO21_M2CENTRAL
        credentials {
            username "$nexusUserName"
            password "$nexusUserPassword"
        }
    }
    //  mavenCentral()
}
/*
rewrite {
    configFile = file("jul-to-slf4j.yml")
    activeRecipe('org.openrewrite.jul.ToSlf4j')
}
*/


dependencies {
    // implementation 'org.openrewrite:rewrite-javascript:8.37.3'
    // implementation 'org.openrewrite:rewrite-logging:8.37.3'
    implementation 'org.slf4j:slf4j-api:2.0.16'

    compileOnly 'com.google.guava:guava:18.0'
    compileOnly 'org.jetbrains:annotations:26.0.1'


    // testImplementation platform('org.junit:junit-bom:5.10.0')
    // testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'junit:junit:4.13.1'
    testImplementation 'us.abstracta:wiresham:0.2.1'
    testImplementation 'org.assertj:assertj-swing:3.9.2'
    testImplementation 'org.assertj:assertj-core:3.10.0'
}

test {
    useJUnitPlatform()
}
